#CI de Nível 01 - Disparo manual a partir de 1 clique

#Nome que vai aparecer nas opções de pipe
name: 'Execução Manual'

#Regras de dispado da execução (triggers)
#gatilho de execução manual = workflow_dispatch

on:
  workflow_dispatch:

jobs:
  #Descrição do job
  e2e-tests:
    #máquina que o job vai executar
    runs-on: ['ubuntu-latest']

    #passo a passo das ações do job
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Testes E2E (end-to-end)
        run: npx cypress run

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./cypress/reports
